projectid = "deft-ocean-413923"
prefix = "mcit-philippe"
bucket_admin = "terraform-auth-test@deft-ocean-413923.iam.gserviceaccount.com"
account_id = "service-account-id"
display_name = "terraform-auth-test"
service_account  = "terraform-auth-test@deft-ocean-413923.iam.gserviceaccount.com"
